<?php
/**
 * Real-world Quiz Data for Seeding
 */

$quizzes_data = [
    [
        'title' => 'History',
        'description' => 'Test your knowledge on world history, ancient civilizations, and modern events.',
        'questions' => [
            ['q' => 'Who was the first President of the United States?', 'options' => ['George Washington', 'Thomas Jefferson', 'John Adams', 'Benjamin Franklin'], 'correct' => 0],
            ['q' => 'In which year did World War II end?', 'options' => ['1942', '1945', '1948', '1950'], 'correct' => 1],
            ['q' => 'Which empire was ruled by Julius Caesar?', 'options' => ['Greek Empire', 'Roman Empire', 'Ottoman Empire', 'Persian Empire'], 'correct' => 1],
            ['q' => 'The French Revolution started in which year?', 'options' => ['1776', '1789', '1804', '1815'], 'correct' => 1],
            ['q' => 'Who was the first woman to win a Nobel Prize?', 'options' => ['Marie Curie', 'Mother Teresa', 'Florence Nightingale', 'Ada Lovelace'], 'correct' => 0],
            ['q' => 'The Titanic sank in which year?', 'options' => ['1905', '1912', '1918', '1925'], 'correct' => 1],
            ['q' => 'Who was the leader of the Soviet Union during World War II?', 'options' => ['Vladimir Lenin', 'Joseph Stalin', 'Leon Trotsky', 'Nikita Khrushchev'], 'correct' => 1],
            ['q' => 'In which year did the Berlin Wall fall?', 'options' => ['1987', '1989', '1991', '1993'], 'correct' => 1],
            ['q' => 'Which ancient civilization built the pyramids?', 'options' => ['Mayans', 'Egyptians', 'Mesopotamians', 'Aztecs'], 'correct' => 1],
            ['q' => 'Who is credited with discovering America in 1492?', 'options' => ['Amerigo Vespucci', 'Christopher Columbus', 'Ferdinand Magellan', 'Vasco da Gama'], 'correct' => 1],
            ['q' => 'The Magna Carta was signed in which year?', 'options' => ['1066', '1215', '1492', '1776'], 'correct' => 1],
            ['q' => 'Who was the primary author of the Declaration of Independence?', 'options' => ['George Washington', 'Thomas Jefferson', 'Abraham Lincoln', 'John Hancock'], 'correct' => 1],
            ['q' => 'The industrial revolution began in which country?', 'options' => ['France', 'USA', 'Germany', 'Great Britain'], 'correct' => 3],
            ['q' => 'Who was the first man to step on the moon?', 'options' => ['Buzz Aldrin', 'Neil Armstrong', 'Yuri Gagarin', 'Michael Collins'], 'correct' => 1],
            ['q' => 'The Ottoman Empire was centered in which modern-day country?', 'options' => ['Greece', 'Iran', 'Turkey', 'Egypt'], 'correct' => 2],
            ['q' => 'In which year did the civil war in the United States begin?', 'options' => ['1850', '1861', '1865', '1870'], 'correct' => 1],
            ['q' => 'Who was the Queen of Egypt who had an affair with Mark Antony?', 'options' => ['Nefertiti', 'Cleopatra', 'Hatshepsut', 'Arsinoe'], 'correct' => 1],
            ['q' => 'The Renaissance began in which country?', 'options' => ['France', 'Spain', 'Italy', 'Netherlands'], 'correct' => 2],
            ['q' => 'Who was the King of Macedonia who conquered the Persian Empire?', 'options' => ['Alexander the Great', 'Philip II', 'Leonidas', 'Xerxes'], 'correct' => 0],
            ['q' => 'The Apartheid system was a policy of racial segregation in which country?', 'options' => ['USA', 'Australia', 'South Africa', 'India'], 'correct' => 2],
        ]
    ],
    [
        'title' => 'Cricket',
        'description' => 'Are you a cricket fan? Solve these MCQs about the gentleman\'s game.',
        'questions' => [
            ['q' => 'In what city would you find Edgbaston Stadium?', 'options' => ['London', 'Manchester', 'Birmingham', 'Leeds'], 'correct' => 2],
            ['q' => 'The Ashes is a Test cricket series between which two countries?', 'options' => ['England and India', 'Australia and South Africa', 'England and Australia', 'India and Pakistan'], 'correct' => 2],
            ['q' => 'How many bails sit on top of the cricket stumps?', 'options' => ['One', 'Two', 'Three', 'Four'], 'correct' => 1],
            ['q' => 'Which team won the first ICC Men\'s Cricket World Cup in 1975?', 'options' => ['Australia', 'England', 'West Indies', 'India'], 'correct' => 2],
            ['q' => 'What does \'LBW\' stand for in cricket?', 'options' => ['Long Ball Wide', 'Leg Before Wicket', 'Last Batsman Waiting', 'Leg Break Wicket'], 'correct' => 1],
            ['q' => 'How many players are there in a cricket team on the field?', 'options' => ['10', '11', '12', '9'], 'correct' => 1],
            ['q' => 'What is a \'Yorker\' in cricket?', 'options' => ['A type of bat', 'A delivery aimed at the batsman\'s feet', 'A fielding position', 'A type of dismissal'], 'correct' => 1],
            ['q' => 'Which country\'s national cricket team is known as \'The Proteas\'?', 'options' => ['Australia', 'South Africa', 'New Zealand', 'West Indies'], 'correct' => 1],
            ['q' => 'What is the length of a cricket pitch from stumps to stumps?', 'options' => ['18 yards', '20 yards', '22 yards', '24 yards'], 'correct' => 2],
            ['q' => 'When an umpire raises both arms straight above his head, what does it signify?', 'options' => ['A four has been scored', 'A six has been scored', 'The batsman is out', 'It\'s a no-ball'], 'correct' => 1],
            ['q' => 'Who is known as the "God of Cricket"?', 'options' => ['Viv Richards', 'Sachin Tendulkar', 'Don Bradman', 'Virat Kohli'], 'correct' => 1],
            ['q' => 'Which player has the highest individual score in Test cricket?', 'options' => ['Matthew Hayden', 'Brian Lara', 'Chris Gayle', 'Ben Stokes'], 'correct' => 1],
            ['q' => 'How many balls are there in an over?', 'options' => ['5', '6', '8', '10'], 'correct' => 1],
            ['q' => 'Which ground is known as the "Home of Cricket"?', 'options' => ['The Oval', 'Lord\'s', 'MCG', 'Eden Gardens'], 'correct' => 1],
            ['q' => 'Who was the captain of the Indian team that won the 1983 World Cup?', 'options' => ['Sunil Gavaskar', 'Kapil Dev', 'Ravi Shastri', 'Mohinder Amarnath'], 'correct' => 1],
            ['q' => 'What is the nickname of the Australian cricket team?', 'options' => ['The Baggy Greens', 'The Kiwis', 'The Lions', 'The Tigers'], 'correct' => 0],
            ['q' => 'Which bowler has taken the most wickets in Test cricket history?', 'options' => ['Shane Warne', 'Anil Kumble', 'Muttiah Muralitharan', 'Glenn McGrath'], 'correct' => 2],
            ['q' => 'A "Hat-trick" in cricket is when a bowler takes how many wickets in consecutive balls?', 'options' => ['2', '3', '4', '5'], 'correct' => 1],
            ['q' => 'Which country hosted the 2023 ICC Cricket World Cup?', 'options' => ['Australia', 'England', 'India', 'South Africa'], 'correct' => 2],
            ['q' => 'What is a "Duck" in cricket?', 'options' => ['A type of shot', 'A batsman getting out for zero', 'A fielding error', 'A type of pitch'], 'correct' => 1],
        ]
    ],
    [
        'title' => 'Football',
        'description' => 'The beautiful game - how much do you know about world football?',
        'questions' => [
            ['q' => 'Which country won the first-ever FIFA World Cup in 1930?', 'options' => ['Brazil', 'Italy', 'Uruguay', 'Germany'], 'correct' => 2],
            ['q' => 'Which club has won the most UEFA Champions League titles?', 'options' => ['FC Barcelona', 'Liverpool FC', 'AC Milan', 'Real Madrid'], 'correct' => 3],
            ['q' => 'Who is the all-time top scorer in the history of the Premier League?', 'options' => ['Wayne Rooney', 'Alan Shearer', 'Sergio Agüero', 'Thierry Henry'], 'correct' => 1],
            ['q' => 'Which player is known as "CR7"?', 'options' => ['Lionel Messi', 'Cristiano Ronaldo', 'Ronaldinho', 'Pelé'], 'correct' => 1],
            ['q' => 'What is the maximum number of players allowed on the field from each team during a match?', 'options' => ['9', '10', '11', '12'], 'correct' => 2],
            ['q' => 'Which stadium is known as "The Theatre of Dreams"?', 'options' => ['Wembley', 'Old Trafford', 'Camp Nou', 'Allianz Arena'], 'correct' => 1],
            ['q' => 'Who scored the "Hand of God" goal in the 1986 World Cup?', 'options' => ['Pelé', 'Diego Maradona', 'Michel Platini', 'Zinedine Zidane'], 'correct' => 1],
            ['q' => 'Which country has won the most FIFA World Cup titles?', 'options' => ['Germany', 'Italy', 'Brazil', 'Argentina'], 'correct' => 2],
            ['q' => 'In which year was FIFA established?', 'options' => ['1900', '1904', '1910', '1920'], 'correct' => 1],
            ['q' => 'Who is the only goalkeeper to have won the Ballon d\'Or award?', 'options' => ['Iker Casillas', 'Gianluigi Buffon', 'Manuel Neuer', 'Lev Yashin'], 'correct' => 3],
            ['q' => 'Which player has won the most Ballon d\'Or awards?', 'options' => ['Cristiano Ronaldo', 'Lionel Messi', 'Johan Cruyff', 'Michel Platini'], 'correct' => 1],
            ['q' => 'What is the duration of a standard football match?', 'options' => ['80 mins', '90 mins', '100 mins', '120 mins'], 'correct' => 1],
            ['q' => 'Which league is considered the top flight of English football?', 'options' => ['Championship', 'Premier League', 'League One', 'La Liga'], 'correct' => 1],
            ['q' => 'What color card does a referee show to send a player off?', 'options' => ['Yellow', 'Red', 'Blue', 'Green'], 'correct' => 1],
            ['q' => 'Which country hosted the 2022 FIFA World Cup?', 'options' => ['Russia', 'Brazil', 'Qatar', 'USA'], 'correct' => 2],
            ['q' => 'Who is the manager of Manchester City (as of 2023)?', 'options' => ['Jurgen Klopp', 'Pep Guardiola', 'Thomas Tuchel', 'Carlo Ancelotti'], 'correct' => 1],
            ['q' => 'What is the nickname of the Italian national football team?', 'options' => ['Les Bleus', 'Azzurri', 'La Roja', 'Seleção'], 'correct' => 1],
            ['q' => 'Which African country was the first to reach a World Cup semi-final?', 'options' => ['Cameroon', 'Senegal', 'Ghana', 'Morocco'], 'correct' => 3],
            ['q' => 'What does VAR stand for in football?', 'options' => ['Visual Assistant Review', 'Video Assistant Referee', 'Velocity Action Replay', 'Virtual Assistant Referee'], 'correct' => 1],
            ['q' => 'How many teams participated in the 2022 FIFA World Cup group stage?', 'options' => ['24', '32', '48', '16'], 'correct' => 1],
        ]
    ],
    [
        'title' => 'Gaming',
        'description' => 'Level up your gaming knowledge with these MCQs about video games.',
        'questions' => [
            ['q' => 'In the game "Super Mario Bros.," what is the name of Mario\'s brother?', 'options' => ['Wario', 'Luigi', 'Bowser', 'Yoshi'], 'correct' => 1],
            ['q' => 'What is the name of the protagonist in the game "The Legend of Zelda"?', 'options' => ['Ganondorf', 'Zelda', 'Link', 'Epona'], 'correct' => 2],
            ['q' => 'Which classic arcade game features ghosts named Blinky, Pinky, Inky, and Clyde?', 'options' => ['Space Invaders', 'Donkey Kong', 'Galaga', 'Pac-Man'], 'correct' => 3],
            ['q' => 'What does NES stand for?', 'options' => ['Nintendo Entertainment System', 'New Electronic Software', 'National Entertainment Software', 'Nintendo Electronic System'], 'correct' => 0],
            ['q' => 'What was the first commercially available video game?', 'options' => ['Space Invaders', 'Pong', 'Pac-Man', 'Asteroids'], 'correct' => 1],
            ['q' => 'Which game features a character named Kratos?', 'options' => ['Assassin\'s Creed', 'Uncharted', 'Tomb Raider', 'God of War'], 'correct' => 3],
            ['q' => 'What is the green crystal that hovers over heads in The Sims called?', 'options' => ['SimStone', 'Plumbob', 'LifeGem', 'Green Shard'], 'correct' => 1],
            ['q' => 'Which company developed the "Grand Theft Auto" series?', 'options' => ['Ubisoft', 'Rockstar Games', 'EA Sports', 'Activision'], 'correct' => 1],
            ['q' => 'What is the highest-selling video game of all time?', 'options' => ['Minecraft', 'Tetris', 'GTA V', 'Super Mario Bros.'], 'correct' => 0],
            ['q' => 'In "League of Legends," what is the primary map called?', 'options' => ['The Abyss', 'Summoner\'s Rift', 'Shadow Isles', 'Crystal Scar'], 'correct' => 1],
            ['q' => 'Which platform is "The Last of Us" exclusive to?', 'options' => ['Xbox', 'PC', 'PlayStation', 'Nintendo Switch'], 'correct' => 2],
            ['q' => 'Who is the creator of "Metal Gear Solid"?', 'options' => ['Shigeru Miyamoto', 'Hideo Kojima', 'John Carmack', 'Will Wright'], 'correct' => 1],
            ['q' => 'What is the name of the fictional city in "BioShock"?', 'options' => ['Columbia', 'Rapture', 'Liberty City', 'Gotham'], 'correct' => 1],
            ['q' => 'Which battle royale game features "building" as a core mechanic?', 'options' => ['PUBG', 'Apex Legends', 'Fortnite', 'Warzone'], 'correct' => 2],
            ['q' => 'What is the name of the main character in "Halo"?', 'options' => ['Marcus Fenix', 'Commander Shepard', 'Master Chief', 'Doomguy'], 'correct' => 2],
            ['q' => 'Which game is known for the phrase "Praise the Sun"?', 'options' => ['Skyrim', 'The Witcher', 'Dark Souls', 'Bloodborne'], 'correct' => 2],
            ['q' => 'What is the name of the handheld console released by Valve in 2022?', 'options' => ['Steam Deck', 'Valve Case', 'G-Boy', 'Portal Player'], 'correct' => 0],
            ['q' => 'Which Pokemon was the first to be designed?', 'options' => ['Pikachu', 'Bulbasaur', 'Rhydon', 'Mew'], 'correct' => 2],
            ['q' => 'What is the name of the world in "World of Warcraft"?', 'options' => ['Tamriel', 'Azeroth', 'Hyrule', 'Sanctuary'], 'correct' => 1],
            ['q' => 'Which studio created "The Witcher" game series?', 'options' => ['Bethesda', 'BioWare', 'CD Projekt Red', 'Naughty Dog'], 'correct' => 2],
        ]
    ],
    [
        'title' => 'General Knowledge',
        'description' => 'A bit of everything for everyone. Test your general awareness.',
        'questions' => [
            ['q' => 'What is the capital of France?', 'options' => ['Berlin', 'Madrid', 'Paris', 'Rome'], 'correct' => 2],
            ['q' => 'Which planet is known as the "Red Planet"?', 'options' => ['Venus', 'Mars', 'Jupiter', 'Saturn'], 'correct' => 1],
            ['q' => 'What is the largest ocean on Earth?', 'options' => ['Atlantic', 'Indian', 'Arctic', 'Pacific'], 'correct' => 3],
            ['q' => 'Who wrote "Romeo and Juliet"?', 'options' => ['Charles Dickens', 'William Shakespeare', 'Mark Twain', 'Jane Austen'], 'correct' => 1],
            ['q' => 'What is the chemical symbol for water?', 'options' => ['CO2', 'H2O', 'NaCl', 'O2'], 'correct' => 1],
            ['q' => 'Which scientist proposed the theory of relativity?', 'options' => ['Isaac Newton', 'Galileo Galilei', 'Albert Einstein', 'Stephen Hawking'], 'correct' => 2],
            ['q' => 'What is the smallest country in the world?', 'options' => ['Monaco', 'Malta', 'Vatican City', 'San Marino'], 'correct' => 2],
            ['q' => 'In which continent is the Sahara Desert located?', 'options' => ['Asia', 'Africa', 'Australia', 'South America'], 'correct' => 1],
            ['q' => 'What is the hardest natural substance on Earth?', 'options' => ['Gold', 'Iron', 'Diamond', 'Granite'], 'correct' => 2],
            ['q' => 'Who painted the "Mona Lisa"?', 'options' => ['Pablo Picasso', 'Vincent van Gogh', 'Leonardo da Vinci', 'Michelangelo'], 'correct' => 2],
            ['q' => 'What is the currency of Japan?', 'options' => ['Won', 'Yuan', 'Yen', 'Ringgit'], 'correct' => 2],
            ['q' => 'Which element has the atomic number 1?', 'options' => ['Helium', 'Oxygen', 'Hydrogen', 'Carbon'], 'correct' => 2],
            ['q' => 'What is the longest river in the world?', 'options' => ['Amazon', 'Nile', 'Yangtze', 'Mississippi'], 'correct' => 1],
            ['q' => 'How many continents are there?', 'options' => ['5', '6', '7', '8'], 'correct' => 2],
            ['q' => 'What is the largest mammal in the world?', 'options' => ['Elephant', 'Blue Whale', 'Giraffe', 'Hippopotamus'], 'correct' => 1],
            ['q' => 'Which organ in the human body is responsible for pumping blood?', 'options' => ['Brain', 'Lungs', 'Heart', 'Liver'], 'correct' => 2],
            ['q' => 'Who is the author of the "Harry Potter" series?', 'options' => ['J.R.R. Tolkien', 'J.K. Rowling', 'George R.R. Martin', 'C.S. Lewis'], 'correct' => 1],
            ['q' => 'What is the main gas found in the Earth\'s atmosphere?', 'options' => ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Argon'], 'correct' => 2],
            ['q' => 'Which country is famous for its maple syrup?', 'options' => ['USA', 'Canada', 'Sweden', 'Norway'], 'correct' => 1],
            ['q' => 'What is the boiling point of water in Celsius?', 'options' => ['90°C', '100°C', '110°C', '120°C'], 'correct' => 1],
        ]
    ]
];
